### ISSUE TITLE
Typos in Unit 1 - Vision

### ISSUE THREAD

**Issue by michaelshekasta** [johko/computer-vision-course#233]
His face reflect -> His face reflects
unsual -> unusual
atire -> attire

@johko

**Comment by johko** [comment]
I think concerning typos it would be good to just create PRs with the corrected words, this way it is easiest to find. Because from this issue I'm not really sure where the words are that should be fixed.

You can create a PR for each unit, or if there aren't many typos (lets say <10) in the unit, a PR for several units

**Comment by bellabf** [comment]
I've adressed them here: https://github.com/johko/computer-vision-course/pull/237
