### ISSUE TITLE
Chapter Discussion: Fundamentals of Computer Vision

### ISSUE THREAD

**Issue by seshupavan** [johko/computer-vision-course#38]
Hello everyone,

The topic Fundamentals of Computer Vision is going to be the first section of the course, so our team planned to keep it as engaging and informative as possible, so we came up with a simple theme of explaining using "**What, Why and How's of computer vision**" and came up with the following curriculum.

1. Why Computer Vision? [motivation.mdx]

- [ ] The perspective of vision
- [ ] Significance of Vision to Humans
- [ ] The motivation behind creating artificial systems capable of simulating human vision and cognition

2. What is computer vision? [defination.mdx]

- [ ] The core of what computer vision is
- [ ] Historical definition
- [ ] Deep learning and the computer vision renaissance
- [ ] Distinction between human and computer vision systems
- [ ] Relation to the field of machine learning and image processing
- [ ] Introduction to image understanding at different levels

3. Computer Vision in the Wild ( How) [applications.mdx]

- [ ] Problems, challenges, and objectives of CV in the real world (examples of problems that computer vision tries to address)
- [ ] A high-level overview of computer vision systems with examples (one or two)
- [ ] Ethical considerations

----
Team members - @seshu-pavan @bellabf, @froestiago @aman06012003 @chiho-5
bcc - @johko @lunarflu @merveenoyan @MKhalusova 

We have one question for now: are you expecting us to write coded tutorials? We created this to include storytelling, definitions and images mostly.

We are well aware that this is an iterative project, so any feedback, tips and suggestions the HF team provides will give us a chance to
improve our progress.

Best,
Fundamentals Team

**Comment by lunarflu** [comment]
Great draft from the Fundamentals Team! 🤗 🌏 I think this is absolutely the right approach, making sure to lay the groundwork so beginners know exactly why CV is needed at all, exploring the nuances of sight, the limitations of hardcoded systems.

Some comments 👇 

> [defination.mdx]

definition.mdx

> What is computer vision?

What is Computer Vision?

> What is computer vision? [defination.mdx]
 The core of what computer vision is
 Historical definition
 Deep learning and the computer vision renaissance
 Distinction between human and computer vision systems
 Relation to the field of machine learning and image processing
 Introduction to image understanding at different levels
Computer Vision in the Wild ( How) [applications.mdx]
 Problems, challenges, and objectives of CV in the real world (examples of problems that computer vision tries to address)

Here I would make sure to include some explicit comparison of pure programming approaches vs. ML approaches when trying to create systems that can see similar to humans. The key here might be something like: 

"We're born able to see without needing to turn that ability on or off; We don't know how to explain how we see; We don't know how to tell a system how to see, since sight is very complex; Some other, more robust method is needed instead of hard coding these systems" -> ML, CV

**Comment by MKhalusova** [comment]
re: 
`We have one question for now: are you expecting us to write coded tutorials? `

I don't think it's necessary to have code examples in this introductory chapter, but you can embed some demos from Space to illustrate some of the applications/tasks. This can make the chapter a little more engaging, and give learners a taste of what they will be able to build themselves later on. 

Here's an example of how to embed a demo into markdown so that doc-builder builds it properly: 

```
<iframe
	src="https://openai-whisper.hf.space"
	frameborder="0"
	width="850"
	height="450">
</iframe>
```

**Comment by johko** [comment]
Great outline :hugs:
I'm really looking forward to this part, as it also is what I would have chosen to write :slightly_smiling_face: 

I also think you don't need much code for it. But as it is the introduction it would be great if you can also reference the other parts of the course while talking about topics like "We will go into more details on Ethics and Biases in Section 12", so the course participants get a bit of an idea what awaits them.
